[project]
name = "conan-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Awareness10", email = "robmart99@gmail.com" }
]
requires-python = ">=3.12.12"
dependencies = [
    "conan>=2.33.0",
]

[project.scripts]
conan-dev = "conan_dev:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
